### ISSUE TITLE
We will probably need to install RSGISLIB

### ISSUE THREAD

**Issue by alexgleith** [digitalearthafrica/deafrica-sandbox#2]
RSGISLIB is used in a few notebooks, and while it really should be removed, it's not been removed yet.

Installing is hard though, and it may be better to refactor notebooks to no longer require it.

Here's the docs: http://rsgislib.org/

**Comment by lgkgh** [comment]
Hi @alexgleith 

RSGISLIB has been added to the image. Please test.

**Comment by fangfy** [comment]
@lgkgh got the below error when running "from rsgislib.segmentation import segutils". I don't think we use this in any notebook now, so we don't have to worry about this for the sandbox.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_68/965852656.py in <module>
----> 1 from rsgislib.segmentation import segutils

/usr/local/lib/python3.8/dist-packages/rsgislib/segmentation/__init__.py in <module>
     31 
     32 # import the C++ extension into this level
---> 33 from ._segmentation import *
     34 
     35 

ImportError: /usr/local/lib/python3.8/dist-packages/rsgislib/segmentation/_segmentation.so: undefined symbol: _ZN10GDALDriver6CreateEPKciii12GDALDataTypePPc
