### ISSUE TITLE
Test whether we can remove NodeJS

### ISSUE THREAD

**Issue by alexgleith** [digitalearthafrica/deafrica-sandbox#3]
https://github.com/digitalearthafrica/deafrica-sandbox/blob/04ec1c59ccdb591941a2a00d0291f89f72e9e0f7/docker/Dockerfile#L6

**Comment by lgkgh** [comment]
Hi @alexgleith 

NodeJS is a requirement for jupyterlab-theme-toggle.

![image](https://user-images.githubusercontent.com/106655586/173373270-36d59049-455f-4740-8b6f-65cf82c21ab6.png)
