### ISSUE TITLE
No shell set in DEV

### ISSUE THREAD

**Issue by fangfy** [digitalearthafrica/deafrica-sandbox#5]
**Describe the bug**
No shell is set in the DEV sandbox terminal. In PROD, it looks like the default is bash.

**To Reproduce**
In the terminal, "echo $SHELL" returns nothing.

**Expected behavior**
Set default shell to bash.

**Screenshots**
-

**Additional context**
Up/down keys, auto complete etc don't work in DEV terminal.

**Comment by lgkgh** [comment]
Hi @fangfy 

$SHELL is now set. Please test.

**Comment by fangfy** [comment]
> Hi @fangfy
> 
> $SHELL is now set. Please test.

Yes, it's working in dev. Thanks!
